Proximate analysis importer
karilint/mammalbase pull request #94
Opened 2024-03-06 10:30 UTC by masiro918

And some refactoring for functions in tools.py

2024-03-06 11:17 UTC, masiro918 commented
Tools ja checker -tiedostot poistettu.

2024-03-06 12:59 UTC, MineTech0 requested changes

2024-03-06 12:59 UTC, MineTech0 commented on app/imports/importers/base_importer.py
> +    def make_harvard_citation_journalarticle(title, d, authors, year, container_title, volume, issue, page):
tyypit

2024-03-06 12:59 UTC, MineTech0 commented on app/imports/importers/base_importer.py
> +    def convert_empty_values_pa(self, row, headers, pa_item_dict):
Ei kuulu base importeriin

2024-03-06 12:59 UTC, MineTech0 commented on app/imports/importers/base_importer.py
> +    def create_return_data(self, tsn, scientific_name, status='valid'):
Nämä tästä alemmas ei kuulu base importeriin

2024-03-06 12:59 UTC, MineTech0 commented on app/imports/validation_lib/base_validation.py
> +        rule = rule.replace("or", "|")
Ei tälläsii viritelmii regex suoraan

2024-03-07 12:51 UTC, masiro918 commented on app/imports/validation_lib/base_validation.py
> +        rule = rule.replace("or", "|")
Tämä oli tosiaan pieni ongelma. Meidän käyttämä sanakirja-perusteinen validointi lukee |-merkit erillisiksi säännöksi, jolloin tolppaa ei voi käyttää regexissä. Ehkä parempi vaihtoehto vois olla, että sääntöjen erotin ei olisi tolppa vaan jokin muu, jolloin voitaisiin käyttää _oikeaa_ regexiä eikä tarvis käyttää tollasta viritelmää

2024-03-07 13:26 UTC, A00N commented on app/imports/importers/base_importer.py
> +    def make_harvard_citation_journalarticle(title, d, authors, year, container_title, volume, issue, page):
Imo tyypit on turhia

2024-03-07 13:27 UTC, A00N commented on app/imports/importers/base_importer.py
> +    def convert_empty_values_pa(self, row, headers, pa_item_dict):
Tälle voisi tulevaisuudessa miettiä mihin nuo menisi. Tähän hätään mielestäni voi olla tuolla.

2024-03-13 09:45 UTC, MineTech0 commented on app/tests/test_views.py
> +    def test_import_pa_post(self):
Ei näin vaan tiedostot valmiiksi ja sitten avaa ne

2024-03-15 11:31 UTC, masiro918 commented on app/imports/validation_lib/base_validation.py
> +        rule = rule.replace("or", "|")
Nyt on sellainen viritelmä, että jos sääntö on hipsujen sisällä, se kokonaisuutenaan on yksi sääntö. Toteuttettu split_rules-funktioon. Eli tota or-viritelmää ei enää ole.

2024-03-15 11:32 UTC, masiro918 commented on app/imports/importers/base_importer.py
> +    def create_return_data(self, tsn, scientific_name, status='valid'):
BaseImporteria on nyt siistitty

2024-03-15 11:33 UTC, masiro918 commented on app/tests/test_views.py
> +    def test_import_pa_post(self):
Tiedostot löytyvät nyt assets-hakemiston takaa. Toimii myös CI-putkessa

2024-03-15 16:06 UTC, MineTech0 commented on app/imports/importers/proximate_analysis_importer.py
> +    def generate_standard_values_pa(self, items):
Tämä ei kuulu tänne koska sitä ei käytetä importissa siirrä se johon utils tiedostoon oikeaan kohtaan

2024-03-15 16:06 UTC, MineTech0 commented on app/mb/views/main.py
> +            bi = BaseImporter()
Ei importeria

2024-03-19 08:22 UTC, masiro918 commented on app/imports/importers/proximate_analysis_importer.py
> +    def generate_standard_values_pa(self, items):
Korjattu

2024-03-19 08:22 UTC, masiro918 commented on app/mb/views/main.py
> +            bi = BaseImporter()
Korjattu

2024-03-20 09:34 UTC, MineTech0 commented on app/pa_false_test.tsv
Nämä tiedostot on nytten kahdessa paikkaa

2024-03-27 09:17 UTC, merged